services:
    _defaults:
        autowire: true
        autoconfigure: true

    # UserInterface: CLI

    AML\UserInterface\CLI\Command\:
        resource: '../src/UserInterface/CLI/Command'

    # Application layer

    AML\Application\Service\:
        resource: '../src/Application/Service'
        exclude: '*Input.php'

    # Domain layer

    AML\Domain\Repository\SearchUrlRepository:
        class: AML\Infrastructure\Domain\Repository\SymfonyCrawlerUrlRepository
        arguments: ['@Symfony\Contracts\HttpClient\HttpClientInterface']

    AML\Domain\Repository\InfoUrlRepository:
        class: AML\Infrastructure\Domain\Repository\PostgressInfoUrlRepository

    AML\Domain\Service\PageFinder:
        arguments:
            - '@AML\Domain\Repository\InfoUrlRepository'
            - '@AML\Domain\Repository\SearchUrlRepository'


    # Third party

    Psr\Log\LoggerInterface:
        factory: '@monolog.logger'

    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: Symfony\Component\HttpClient\HttpClient::create
