services:
    _defaults:
        autowire: true
        autoconfigure: true

    # UserInterface: CLI

    AML\UserInterface\CLI\Command\:
        resource: '../src/UserInterface/CLI/Command'

    # Application layer

    AML\Application\Service\:
        resource: '../src/Application/Service'
        exclude: '*Input.php'

    AML\Application\Bus\CommandBus:
      class: '@simple_bus.command_bus'

    AML\Application\Bus\MyHandler:
      class: AML\Application\Bus\MyHandler
      tags:
        - { name: command_handler, handles: MediaManager\Application\Bus\ProcessPageCommand }

    # Domain layer

    AML\Domain\Repository\SearchUrlRepository:
        class: AML\Infrastructure\Domain\Repository\SymfonyCrawlerUrlRepository
        arguments: ['@Symfony\Contracts\HttpClient\HttpClientInterface']

    AML\Domain\Repository\InfoUrlRepository:
        class: AML\Infrastructure\Domain\Repository\DoctrineInfoUrlRepository
        factory: ["@doctrine", getRepository]
        arguments: ["DomainModel:Page"]

    # Third party

    Psr\Log\LoggerInterface:
        factory: '@monolog.logger'

    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: Symfony\Component\HttpClient\HttpClient::create
