AML\Domain\ValueObject\Page:
  type: entity
  repositoryClass: AML\Infrastructure\Domain\Repository\DoctrineInfoUrlRepository
  table: pages
  embedded:
    headers:
      class: AML\Domain\ValueObject\SearchUrlHeaderCollection
      columnPrefix: false
  id:
    url:
      type: search_url_type
      column: url
  fields:
    reference:
      type: uuid_string
      nullable: false
      column: reference
